### ISSUE TITLE
Client Disconnects when changing clothing

### ISSUE THREAD

**Issue by Daovala** [kenigvovan/CAN_Jewelry#5]
Repeatable disconnect/minor crash occurs when non armor items are changed out on our server. Updated this mod and primitive survival other never had this issue prior

Adding server side error as it was all I got from the logs between client/server

9.9.2024 10:27:39 [Server Error] Exception: Object reference not set to an instance of an object.
   at canjewelry.src.eb.CANGemBuffAffected.OnSlotModifiedCharacterInv(Int32 i) in C:\Users\koeni\source\repos\can_jewelry\jw\can
jewelry\canjewelry\src\eb\CANGemBuffAffected.cs:line 182
   at Vintagestory.API.Common.InventoryBase.DidModifyItemSlot(ItemSlot slot, ItemStack extractedStack) in VintagestoryApi\Common
\Inventory\InventoryBase.cs:line 480
   at Vintagestory.API.Common.ItemSlot.OnItemSlotModified(ItemStack sinkStack) in VintagestoryApi\Common\Inventory\ItemSlot.cs:l
ine 432
   at Vintagestory.API.Common.ItemSlot.TakeOutWhole() in VintagestoryApi\Common\Inventory\ItemSlot.cs:line 145
   at Vintagestory.API.Common.ItemSlot.TryPutInto(ItemSlot sinkSlot, ItemStackMoveOperation& op) in VintagestoryApi\Common\Inven
tory\ItemSlot.cs:line 229
   at Vintagestory.API.Common.ItemSlot.ActivateSlotLeftClick(ItemSlot sourceSlot, ItemStackMoveOperation& op) in VintagestoryApi
\Common\Inventory\ItemSlot.cs:line 359
   at Vintagestory.API.Common.InventoryBase.ActivateSlot(Int32 slotId, ItemSlot sourceSlot, ItemStackMoveOperation& op) in Vinta
gestoryApi\Common\Inventory\InventoryBase.cs:line 436
   at Vintagestory.Common.InventoryNetworkUtil.HandleClientPacket(IPlayer byPlayer, Int32 packetId, Packet_Client packet) in Vin
tagestoryLib\Common\GameContent\Inventory\InventoryNetworkUtil.cs:line 228
   at Vintagestory.Server.ServerSystemInventory.HandleActivateInventorySlot(Packet_Client packet, ConnectedClient client) in Vin
tagestoryLib\Server\Systems\Inventory.cs:line 493
   at Vintagestory.Server.ServerMain.ProcessNetMessage(NetIncomingMessage msg, NetServer mainSocket) in VintagestoryLib\Server\S
erverMainNetworking.cs:line 138

9.9.2024 10:28:33 [Server Error] Exception: Object reference not set to an instance of an object.
   at canjewelry.src.eb.CANGemBuffAffected.OnSlotModifiedCharacterInv(Int32 i) in C:\Users\koeni\source\repos\can_jewelry\jw\can
jewelry\canjewelry\src\eb\CANGemBuffAffected.cs:line 182
   at Vintagestory.API.Common.InventoryBase.DidModifyItemSlot(ItemSlot slot, ItemStack extractedStack) in VintagestoryApi\Common
\Inventory\InventoryBase.cs:line 480
   at Vintagestory.API.Common.ItemSlot.OnItemSlotModified(ItemStack sinkStack) in VintagestoryApi\Common\Inventory\ItemSlot.cs:l
ine 432
   at Vintagestory.API.Common.ItemSlot.TryFlipWith(ItemSlot itemSlot) in VintagestoryApi\Common\Inventory\ItemSlot.cs:line 256
   at Vintagestory.GameContent.ItemWearable.OnHeldInteractStart(ItemSlot slot, EntityAgent byEntity, BlockSelection blockSel, En
titySelection entitySel, Boolean firstEvent, EnumHandHandling& handHandling) in VSSurvivalMod\Item\ItemWearable.cs:line 404
   at Vintagestory.Server.ServerSystemInventory.HandleHandInteraction(Packet_Client packet, ConnectedClient client) in Vintagest
oryLib\Server\Systems\Inventory.cs:line 255
   at Vintagestory.Server.ServerMain.ProcessNetMessage(NetIncomingMessage msg, NetServer mainSocket) in VintagestoryLib\Server\S
erverMainNetworking.cs:line 138

**Comment by Daovala** [comment]
Lastest Update seems to have resolved the issue
